CREATE DATABASE IF NOT EXISTS cdd_db;
USE cdd_db;

CREATE TABLE IF NOT EXISTS cdd (
    id INT AUTO_INCREMENT PRIMARY KEY,
    codigo VARCHAR(255) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    area VARCHAR(255) NOT NULL
);